# This file was generated by GoReleaser. DO NOT EDIT.
cask "gnosis" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "293b82498017ed749dfb197bdecc6bedf33932be065c520e5eb456365fc507ab"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6d1b51ddc341b7e0a537f1ee98b4d3dacf241bbf0da04a43f02a7d5a949a9240"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b428056fe3a9715eb417509bcfcca0085cd28184007bf2f743d9f1806c897255"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9b097fb5e293ee76bab5d2f33873430f0b2bd0cf99b6b77a056934694f071212"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gnosis"
  desc "A knowledge base for what the code can't tell you."
  homepage "https://github.com/skorokithakis/gnosis"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gn"]
    end
  end

  # No zap stanza required

end
