# This file was generated by GoReleaser. DO NOT EDIT.
cask "gnosis" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "e22b7774eb11c72f167b765dc680bb03f979e70660d2492b77ac95cff7f7e2db"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "be1b15728585e17f1820c76f0b80107573a42c7bd2052b83c1bb80384167b572"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "54680f90727f501b1005ebf29ed3ac8d7c2df3c2739bdde8d7ef5144ec45abbb"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e158c7fe46ee06bf571c2531fe21d45a6d8fee5269b52ad0e29484ce50652435"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gnosis"
  desc "A knowledge base for what the code can't tell you."
  homepage "https://github.com/skorokithakis/gnosis"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gn"]
    end
  end

  # No zap stanza required

end
