# This file was generated by GoReleaser. DO NOT EDIT.
cask "gnosis" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "3669c9261d516326e998b364eb14b360e6f181807d49a12307c5b57a811bed5d"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9591cfb1e4e98a29e094e43b10a49b07354e584ac0f3a95838f3245a89f6b4b4"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3c549f0c4f5f87947c7a572890ab88b22a3fa1867b7cc621846fa7e6973c844d"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e43f70ab16345464e3ac4d3ff2e1c8ad8026eaa98ef014b2585c57e8fef94e1c"
      url "https://github.com/skorokithakis/gnosis/releases/download/v#{version}/gnosis_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gnosis"
  desc "A knowledge base for what the code can't tell you."
  homepage "https://github.com/skorokithakis/gnosis"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gn"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gn"]
    end
  end

  # No zap stanza required

end
