# This file was generated by GoReleaser. DO NOT EDIT.
cask "graphe" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f101848a88050294174f0c92ab35824a28b918586394943b63f250d4bad5f6a1"
      url "https://github.com/skorokithakis/graphe/releases/download/v#{version}/graphe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f0cc0fed10906fbcbef7084d39590c4ca306c17093316bf19a962e7bb775794d"
      url "https://github.com/skorokithakis/graphe/releases/download/v#{version}/graphe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "80202c1f166705d7e0fb04288e872dcfd134de3932480986827aa751d8e1d838"
      url "https://github.com/skorokithakis/graphe/releases/download/v#{version}/graphe_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1db804b3946b031a596350474d85f7936bbed6750aae6256a92850e14bc8425d"
      url "https://github.com/skorokithakis/graphe/releases/download/v#{version}/graphe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "graphe"
  desc "Serve a markdown file as a Tufte-style web page with reviewer comments as margin notes."
  homepage "https://github.com/skorokithakis/graphe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "graphe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/graphe"]
    end
  end

  # No zap stanza required

end
