# This file was generated by GoReleaser. DO NOT EDIT.
cask "graphe" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "a921a1787fd90b9b558d22fe170e997af26d964f74c1c0bdeb44e78ca9b0e55b"
      url "https://github.com/skorokithakis/graphe/releases/download/v#{version}/graphe_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f1356740a1a934caf09fb92ce9189d2d488370e0a8debb0a77514263d970dbf"
      url "https://github.com/skorokithakis/graphe/releases/download/v#{version}/graphe_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "83195ff12a74e894c4d2e78e61724f4408351b23c7687d985ad89a8c3b16a1e8"
      url "https://github.com/skorokithakis/graphe/releases/download/v#{version}/graphe_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c505197c713d6c0160c8be7213c20bc57364c65bfd14c9d89c887345f136948"
      url "https://github.com/skorokithakis/graphe/releases/download/v#{version}/graphe_#{version}_linux_arm64.tar.gz"
    end
  end

  name "graphe"
  desc "Serve a markdown file as a Tufte-style web page with reviewer comments as margin notes."
  homepage "https://github.com/skorokithakis/graphe"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "graphe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/graphe"]
    end
  end

  # No zap stanza required

end
